# Generated by Django 3.0.8 on 2020-08-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAppapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_info',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
