# Generated by Django 3.0.8 on 2020-08-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAppapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
