# Generated by Django 3.0.8 on 2020-08-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAppapp1', '0002_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='description',
            field=models.CharField(blank=True, default='Hello There', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
