# Generated by Django 3.0.8 on 2020-08-03 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogAppapp1', '0003_auto_20200803_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
