# Generated by Django 3.0.8 on 2020-07-30 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogAppapp1', '0003_following_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=2000)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
