# Generated by Django 3.0.8 on 2020-07-31 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAppapp1', '0005_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='BlogAppapp1.Groups', to_field='group_id')),
            ],
        ),
    ]
