# Generated by Django 3.0.8 on 2020-08-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAppapp1', '0002_auto_20200802_1122'),
        ('BlogAppapp1', '0008_auto_20200731_1342'),
    ]

    operations = [
    ]
