# Generated by Django 3.0.8 on 2020-08-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAppapp1', '0009_merge_20200802_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='blog_info',
            name='status',
        ),
        migrations.AlterField(
            model_name='blog_info',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
